/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import javax.swing.*;
import BBDspéc.Employe;
import Connection.ConnectionEce;
import Connection.*;
import DAO.DAO;
import DAO.EmployeDAO;
import BBDspéc.Batiment;
import DAO.Requete;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author travail
 */
public class ClasseRequetePanelAuguste extends javax.swing.JPanel {


    private String requeteChoisie = "0";
    private ConnectionEce conn1;//= new ConnectionEce("0","","",""); //erreur
    private ArrayList tabVal = new ArrayList();
    
    public ClasseRequetePanelAuguste(ConnectionEce connIN) {
        initComponents();
        conn1 = connIN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("1 bouton lancement.");

        jButton1.setText("MAJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Requetes 1 à 10, parmis celles du DAO dans la classe requête ");

        jLabel3.setText("Affiche le résultat de la requête dans le tableau");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Requête à choisir", "Requête 1", "Requête 2", "Requête 3", "Requête 4", "Requête 5", "Requête 6", "Requête 7", "Requête 8", "Requête 9", "Requête 10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(354, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    requeteChoisie =  (String)jComboBox1.getSelectedItem();   
    
    //JScrollPane scrollPane = new JScrollPane(jTable1);

    //Recupère le String de la requête choisie.
// TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    /*OBJECTIF:
      Selon la requête, remplir un ArrayList tabVal. 
        Il permettra de remplir un tableauModel de l'interface.
        arrayList length();
        */ 
      //layout.add(new JScrollPane(jTable1));
      

    System.out.println("La requète choisie est "+ requeteChoisie);
    
    if("Requête 1".equals(requeteChoisie))//pour employé
        {
        //ICI TESTE SI LA LISTE DE TOUS LES EMPLOYES EST BIEN ENREGISTREE DANS TABVAL
          //les tests  
            //Requete firstRequete = new Requete(ConnectionEce.getConn());
            //ArrayList<ArrayList> sortie = firstRequete.Requete1();
            
          
        EmployeDAO retourEmployeAll = new EmployeDAO(ConnectionEce.getConn());
            System.out.println("ON VA Y ARRIVER !!! 11111");
            
            ArrayList<Employe> tabVal1 = retourEmployeAll.findall();
            
            System.out.println("ON VA Y ARRIVER !!! 22222");

            String[] entetes = { "No employé","Nom", "Prénom", "Tel", "Adresse" };
            
           DefaultTableModel tableModel = new DefaultTableModel(entetes, 0);
           
           for(int i = 0; i<tabVal1.size();i++)
           {
           System.out.println("ON VA Y ARRIVER !!! 33333");

           Employe emp = new Employe();
           emp =(Employe) tabVal1.get(i);
           System.out.println("ON VA Y ARRIVER !!! 444444");
           
           System.out.println(emp);
           
           Object objectTab[]= {
           emp.getNo_employe(),
           emp.getNom(),
           emp.getPrenom(),
           emp.getTel(),
           emp.getAdresse()
            };
           tableModel.addRow(objectTab);
           }
           /*           
        System.out.println("***Affichage de tout les employés:");
        tabVal.stream().forEach((employe1) -> {
            System.out.println(employe1.toString());
        });*/
        //permet de changer le model du tableau
         JTable leTableau = new JTable();

           leTableau.setModel(tableModel);
           
         JScrollPane scrollPane11 = new JScrollPane(leTableau);
        
         this.add(scrollPane11);  
         scrollPane11.setBounds(50,180,950,500);
          //jTable1.setBounds(null);  
           System.out.println("C'est le find all employé !!! BRAVO e3lik!");  
        // jScrollPane2.setViewportView(jTable1);
        try {
            conn1.fermerConnection();
            //C'est le cas, mais ils sont complètement dans le désordre. 
        } catch (SQLException ex) {
            Logger.getLogger(PanelRequete.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}
