/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import javax.swing.*;
import BBDspéc.Employe;
import Connection.ConnectionEce;
import Connection.*;
import DAO.DAO;
import DAO.EmployeDAO;
import BBDspéc.Batiment;
import DAO.Requete;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author travail
 */
public class PanelRequete extends javax.swing.JPanel {


    private String requeteChoisie = "0";
    private ConnectionEce conn1= new ConnectionEce("0","","",""); //erreur
    private ArrayList tabVal = new ArrayList();
    
    public PanelRequete(ConnectionEce connIN) {
        initComponents();
        conn1 = connIN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("1 bouton lancement.");

        jButton1.setText("MAJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4","Titre 5"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setText("Requetes 1 à 10, parmis celles du DAO dans la classe requête ");

        jLabel3.setText("Affiche le résultat de la requête dans le tableau");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Requête à choisir", "Requête 1", "Requête 2", "Requête 3", "Requête 4", "Requête 5", "Requête 6", "Requête 7", "Requête 8", "Requête 9", "Requête 10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    requeteChoisie =  (String)jComboBox1.getSelectedItem();   
    //Recupère le String de la requête choisie.
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /*OBJECTIF:
      Selon la requête, remplir un ArrayList tabVal. 
        Il permettra de remplir un tableauModel de l'interface.
        arrayList length();
        */ 
      //layout.add(new JScrollPane(jTable1));
      

    System.out.println("La requète choisie est "+ requeteChoisie);
    
    if("Requête 1".equals(requeteChoisie))//pour employé
        {
        //ICI TESTE SI LA LISTE DE TOUS LES EMPLOYES EST BIEN ENREGISTREE DANS TABVAL
            System.out.println("C'est le find all employé !!! BRAVO e3lik!");
          //les tests  
            Requete firstRequete = new Requete(ConnectionEce.getConn());
            ArrayList<ArrayList> sortie = firstRequete.Requete1();
           
           // jTable1 = JTable(valeurs, noms);
      /*  ArrayList<Integer> foo = new ArrayList<Integer>();
        foo.add(1);
        foo.add(1);
        foo.add(2);
        foo.add(3);
        foo.add(5);
       // JTable table = new JTable(new Object[nblignes][columnNames.length], columnNames);

        String[][] contenuJTable = sortie.toArray(new String[sortie.size()][sortie.size()]);
        Object[] sortieT= sortie.toArray(new Object[sortie.size()]);

        String[] bar = foo.toArray(new String[foo.size()]);

System.out.println("bar.length = " + bar.length);
            */
            
            EmployeDAO retourEmployeAll = new EmployeDAO(ConnectionEce.getConn());
            tabVal = retourEmployeAll.findall();
            //int longueurTableau = tabVal.size();
           // tabVal.get(0).size();
             
     
            
      /* objectif : remplir un tableau à deux dimensions pour remplir le JTable.
           Object[][] data  = new Object[5][]();
      
            /*for(int i=0;i<tabVal.size();i++)
                for(int j=0; j<5;j++)
              Object[i][j] data = tabVal;*/
       
        System.out.println("***Affichage de tout les employés:");
        tabVal.stream().forEach((employe1) -> {
            System.out.println(employe1.toString());
        });
        //C'est le cas, mais ils sont complètement dans le désordre. 
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
